### ISSUE TITLE
Questions about ATM_S_insubject_retrieval.py file

### ISSUE THREAD

**Issue by xiuwenwu** [dongyangli-del/EEG_Image_decode#18]
I noticed that when training the ATM_S insubject retrieval task, there are two models involved in this parameter update: 
1. eeg_model; 2. img_model. From what I understand, the img_model is clip model for img features extraction. 
Will updating the clip network parameters during the training process improve the performance of the model a lot?
![pngs](https://github.com/dongyangli-del/EEG_Image_decode/assets/43297148/8469f3a1-6501-461f-b132-d9b60fb90734)

**Comment by dongyangli-del** [comment]
Hi, @xiuwenwu, the CLIP image encoder is called in [eegdatasets_leaveone.py](https://github.com/dongyangli-del/EEG_Image_decode/blob/main/Retrieval/eegdatasets_leaveone.py). The definition of `img_model `shown in your image is only used for testing purposes. In the actual process, img is not projected because training the projector would cause the original knowledge of CLIP to be forgotten.

Therefore, just ignore this function `img_model `.

**Comment by xiuwenwu** [comment]
Thank you for your response!!!
