### ISSUE TITLE
Pretrained weights for Generation_measure

### ISSUE THREAD

**Issue by jonxuxu** [dongyangli-del/EEG_Image_decode#2]
Hi there, after running ATM_S_insubject_retrieval.py we get weights stored in the ATMS_50 dir, such as `Retrieval/models/contrast/ATMS_50/sub-01/03-26_20-35/40.pth`

Where do we create or find the weights to load the state dict in Generation_metrics_sub1.ipynb, when it calls
`eeg_model.load_state_dict(torch.load("models/contrast/ATM_S_reconstruction_scale_0_1000/01-31_23-20/sub-01/40.pth"))`?

I don't believe the ATMS_50 weights work for the ATM_S_reconstruction_scale_0_1000 model since we get an error about dimensions:
```
RuntimeError: Error(s) in loading state_dict for ATM_S_reconstruction_scale_0_1000:
	size mismatch for enc_eeg.0.tsconv.0.weight: copying a param with shape torch.Size([40, 1, 1, 25]) from checkpoint, the shape in current model is torch.Size([40, 1, 1, 5]).
	size mismatch for proj_eeg.0.weight: copying a param with shape torch.Size([1024, 1440]) from checkpoint, the shape in current model is torch.Size([1024, 1840]).
```

**Comment by dongyangli-del** [comment]
@jonxuxu Thank you very much for your continued interest in our work! We recommend that you first run ATM_S_insubject_retrieval.py and save the model weights, then load the model in Generation_metrics_sub1.ipynb and test it. Due to the size limit of the remote warehouse, we cannot directly upload a large number of trained model weights. If necessary, we will consider placing a model repository link on the hugging face. If you have any other questions, please feel free to ask.

**Comment by dongyangli-del** [comment]
@jonxuxu 
As shown in my screenshot, the convolution kernel sizes of _ATM_S_insubject_retrieval.py_ and _ATM_S_reconstruction_scale_0_1000.py_ are actually slightly different.

This is because at the beginning of the network design, we wanted it to have the ability to change lengths and channels. (This is why our model is called ATM, Adaptive Thinking Mapper). In order to allow data of different lengths to be input, we ablated it in the time dimension. The experimental code all uses the design of small convolution kernels, which is slightly different from the code under the retrieval task.

Solution: For example, if you need to run _Generation_metrics_sub1.ipynb_ to generate images, first run _ATM_S_reconstruction_scale_0_1000.py_ instead of _ATM_S_insubject_retrieval.py,_ because the network design of _ATM_S_reconstruction_scale_0_1000.py_ is exactly the same as the network defined in _Generation_metrics_sub1.ipynb_.

![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/d08faa74-7cce-4090-b8a0-cd1d45ff622b)
