### ISSUE TITLE
Running reconstruction metrics

### ISSUE THREAD

**Issue by generic111** [dongyangli-del/EEG_Image_decode#6]
Hi,

I'm trying to run the Reconstruction_Metrics_ATM.ipynb and in it there a path:

`all_images_path = '/home/ldy/Workspace/THINGS/images_set/test_images_tensor/all_images.pt'`

I am unsure where this `all_images.pt` is as it was not generated when I ran ATM_S_reconstruction_scale_0_1000.py and Generation_metric_sub1.ipynb.

**Comment by dongyangli-del** [comment]
@generic111 
Hello, if you can successfully run the previous image generation code Generation_metric_sub{xx}.ipynb, then directly modify the path and run Reconstruction_Metrics_ATM.ipynb to generate the corresponding image_tensors:

![image](https://github.com/dongyangli-del/EEG_Image_decode/assets/62006079/f8f3e3d2-3fab-441f-bc2b-2e3982de4614)

Due to the limitation of the warehouse size, this part of image_tensors could not be uploaded. If you still encounter difficulties, you can contact me again and I will consider uploading image_tensors to google driver.
